// Main-thread AppKit pasteboard authority and one-shot source-language fact.
// No clipboard text is read by a baseline/count probe. No Translation APIs.
// A version its writer marked confidential or momentary (ConcealedType /
// TransientType of the nspasteboard.org convention) is never read.
import Foundation
import AppKit
import NaturalLanguage

// Debug smoke builds compile native/SmokeBridge.swift, which may point the
// same gate at a test-owned named pasteboard. Release never sets it.
var deckSmokeTranslationPasteboard: NSPasteboard? = nil
func deckTranslationPasteboard() -> NSPasteboard { deckSmokeTranslationPasteboard ?? .general }

func onMain<T>(_ body: () -> T) -> T {
    if Thread.isMainThread { return body() }
    return DispatchQueue.main.sync(execute: body)
}

@_cdecl("deck_pasteboard_focused_count")
public func deckPasteboardFocusedCount() -> Int64 {
    onMain {
        guard NSApp.isActive, NSApp.keyWindow != nil else { return -1 }
        return Int64(deckTranslationPasteboard().changeCount)
    }
}

// Markers of the nspasteboard.org convention that say the content must not
// be shown: confidential (a password manager's copy), or on the board only
// for a moment before it is replaced or restored (a text expander's or a
// macro's paste). AutoGeneratedType is not one of them: by that convention
// such content may still be shown as the current content.
let deckPasteboardWithheldTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType"]
    .map { NSPasteboard.PasteboardType($0) }

// What one read of a pasteboard found: its text, nothing readable as text,
// or a version that was not read because of a marker.
enum DeckPasteboardRead: Equatable { case text(String), none, withheld }

// Does any item on `board` carry one of the markers (`types` covers every
// item)? nil when the types cannot be read: then nothing is known.
func deckPasteboardMarked(_ board: NSPasteboard) -> Bool? {
    board.types.map { types in deckPasteboardWithheldTypes.contains { types.contains($0) } }
}

// One read of `board`. The markers are looked for BEFORE the text is asked
// for, so marked text is never read, and again AFTER it: a writer may add
// its marker in a call after the text, and that does not change the
// changeCount. The second look narrows that window; AppKit offers no way to
// close it. Unreadable types are no proof that no marker is there, so then
// nothing is handed over either. `text` is the read itself (tests
// substitute it).
func deckPasteboardRead(_ board: NSPasteboard,
                        text: (NSPasteboard) -> String? = { $0.string(forType: .string) }) -> DeckPasteboardRead {
    guard let marked = deckPasteboardMarked(board) else { return .none }
    if marked { return .withheld }
    let value = text(board)
    guard let late = deckPasteboardMarked(board) else { return .none }
    if late { return .withheld }
    guard let value, !value.contains("\0") else { return .none }
    return .text(value)
}

// `withheld` is set to 1 when the version was skipped for a marker, so that
// the gate can consume it without reporting a failed read.
@_cdecl("deck_pasteboard_read_text")
public func deckPasteboardReadText(_ withheld: UnsafeMutablePointer<Int32>?) -> UnsafeMutablePointer<CChar>? {
    onMain {
        withheld?.pointee = 0
        guard NSApp.isActive, NSApp.keyWindow != nil else { return nil }
        switch deckPasteboardRead(deckTranslationPasteboard()) {
        case .text(let text): return strdup(text)
        case .withheld: withheld?.pointee = 1; return nil
        case .none: return nil
        }
    }
}

// Deck's own Lens copy (Copy Translation, Copy Source, Cmd+C in the result).
// Returns the changeCount that clearContents() produced for THIS write: the
// receipt the clipboard gate uses to exclude exactly this version from
// Copied-text observation. -1 when the write failed.
@_cdecl("deck_pasteboard_write_text")
public func deckPasteboardWriteText(_ text: UnsafePointer<CChar>?) -> Int64 {
    onMain {
        guard let text else { return -1 }
        let board = deckTranslationPasteboard()
        let count = board.clearContents()
        return board.setString(String(cString: text), forType: .string) ? Int64(count) : -1
    }
}

@_cdecl("deck_pasteboard_free")
public func deckPasteboardFree(_ text: UnsafeMutablePointer<CChar>?) { free(text) }

// 1 = dominant English, 2 = dominant Chinese, 0 = unsupported/unknown.
@_cdecl("deck_translation_source_kind")
public func deckTranslationSourceKind(_ source: UnsafePointer<CChar>?) -> Int32 {
    guard let source else { return 0 }
    let recognizer = NLLanguageRecognizer()
    recognizer.processString(String(cString: source))
    switch recognizer.dominantLanguage {
    case .english: return 1
    case .simplifiedChinese, .traditionalChinese: return 2
    default: return 0
    }
}
