//! tmux backend: sidecar discovery, the private `deck` server, config, and
//! raw command execution. Everything deck knows about tmux lives here.
//!
//! # Contract
//! tmux ships INSIDE the app: a statically linked binary (see
//! `binaries/build-tmux.sh`, committed as `binaries/tmux-aarch64-apple-darwin`,
//! bundled+signed via tauri `externalBin`). `tmux_bin()` prefers the sidecar,
//! then Homebrew/MacPorts probes. deck talks to its OWN server (`-L deck`
//! socket) — never version-clashes with a user tmux, and deck sessions don't
//! appear in the user's `tmux ls`. Production debug: `tmux -L deck ls`;
//! source bundles use `tmux -L deck-dev ls`.

use std::io::Write;
use std::process::{Command, Stdio};

use crate::applog;

// ---------- tmux helpers ----------------------------------------------------

/// Absolute path to tmux. The bundled sidecar comes first (zero-dependency
/// installs — a statically linked tmux ships inside the .app); Homebrew /
/// MacPorts are fallbacks for source builds. Apps launched from Finder get
/// launchd's PATH (no /opt/homebrew/bin), so plain "tmux" is last resort.
pub(crate) fn tmux_bin() -> &'static str {
    static BIN: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    BIN.get_or_init(|| {
        let mut candidates: Vec<String> = Vec::new();
        if let Ok(exe) = std::env::current_exe() {
            if let Some(dir) = exe.parent() {
                candidates.push(dir.join("tmux").display().to_string());
            }
        }
        for p in [
            "/opt/homebrew/bin/tmux",
            "/usr/local/bin/tmux",
            "/opt/local/bin/tmux",
        ] {
            candidates.push(p.to_string());
        }
        for c in candidates {
            if std::path::Path::new(&c).exists() {
                // log the CATEGORY, never the absolute path (it can embed
                // the .app location / user directories and ends up in exports)
                applog(&format!("[tmux] using {} binary", tmux_kind_of(&c)));
                return c;
            }
        }
        applog("[tmux] falling back to PATH lookup");
        "tmux".to_string()
    })
}

/// Path-free classification of a tmux binary location, for logs/exports.
pub(crate) fn tmux_kind_of(path: &str) -> &'static str {
    if path == "tmux" {
        "PATH"
    } else if path.starts_with("/opt/homebrew") || path.starts_with("/usr/local") {
        "homebrew"
    } else if path.starts_with("/opt/local") {
        "macports"
    } else {
        "sidecar"
    }
}

pub(crate) fn tmux_kind() -> &'static str {
    tmux_kind_of(tmux_bin())
}

/// deck runs its own tmux server (socket "deck"): the bundled binary never
/// clashes with a user-installed tmux of a different version, and deck's
/// sessions stay out of the user's personal `tmux ls`.
pub(crate) fn socket() -> &'static str {
    static SOCKET: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    SOCKET.get_or_init(|| {
        if crate::launch_args::debug_arg("--smoke-data-dir").is_some() {
            return crate::launch_args::debug_arg("--smoke-tmux-socket")
                .filter(|s| {
                    s.starts_with("deck-smoke")
                        && !s.is_empty()
                        && s.len() <= 48
                        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
                })
                .unwrap_or_else(|| "deck-smoke".into());
        }
        if cfg!(debug_assertions) {
            "deck-dev".into()
        } else {
            "deck".into()
        }
    })
}

/// Server config file: options set via `tmux set -g` die with the server
/// process (a session-less server exits immediately, so boot-time `set`
/// calls raced server restarts and the status bar kept coming back).
/// A -f config is applied at every server spawn, deterministically.
pub(crate) fn tmux_conf() -> String {
    static CONF: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    CONF.get_or_init(|| {
        let deck_dir = crate::datadir::deck_dir();
        let path = deck_dir.join("tmux.conf");
        if let Some(dir) = path.parent() {
            let _ = crate::datadir::create_private_dir(dir);
        }
        let _ = crate::datadir::write_private(&path, tmux_conf_text(&deck_dir).as_bytes());
        path.display().to_string()
    })
    .clone()
}

/// The server defaults every deck tmux server starts with. Intermediate
/// copy-mode selection frames are styled `none` so tmux's cursor-bound
/// highlight never flashes under Deck's own selection overlay; only the
/// copy cursor position is styled.
pub(crate) fn tmux_conf_text(deck_dir: &std::path::Path) -> String {
    format!(
        "# generated by deck — server defaults\n\
         set -g status off\n\
         set -g set-clipboard on\n\
         set -g history-limit 50000\n\
         set -g mode-style 'none'\n\
         set -g copy-mode-selection-style 'none'\n\
         set -g copy-mode-position-style 'reverse'\n\
         set -g copy-mode-position-format ''\n\
         set-environment -g COLORTERM truecolor\n\
         {}",
        status_sock_env_line(deck_dir)
    )
}

/// Run tmux (on the deck server) with output captured — stray stderr must
/// never reach a terminal.
///
/// LANG is pinned to a UTF-8 locale: GUI-launched apps get NO locale env,
/// and under the C locale tmux sanitizes every control character in command
/// output — including the \t field separators poll_sessions parses — to
/// '_', and mangles non-ASCII pane content in capture-pane. (Shipped as the
/// v0.4.16 "board all gray / no separators" bug: dev builds launched from a
/// terminal inherited the shell's LANG and never reproduced it.) pty.rs
/// sets the same for the attach client.
pub(crate) fn tmux(args: &[&str]) -> Result<String, String> {
    let conf = tmux_conf();
    let out = Command::new(tmux_bin())
        .args(["-f", &conf, "-L", socket()])
        .args(args)
        .env("LANG", "en_US.UTF-8")
        .output()
        .map_err(|e| format!("tmux not runnable: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "tmux {} failed: {}",
            args.first().unwrap_or(&""),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// Run tmux with bounded caller-owned bytes on stdin. This is used for shell
/// recovery so private scrollback never appears in argv, an environment
/// variable, or a temporary file. `start-server ; load-buffer ... - ;
/// new-session ...` may be submitted as one batch, which also keeps a newly
/// spawned zero-session server alive until the restored pane exists.
pub(crate) fn tmux_with_stdin(args: &[&str], input: &[u8]) -> Result<String, String> {
    let conf = tmux_conf();
    let mut child = Command::new(tmux_bin())
        .args(["-f", &conf, "-L", socket()])
        .args(args)
        .env("LANG", "en_US.UTF-8")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("tmux not runnable: {e}"))?;
    let write_result = child
        .stdin
        .as_mut()
        .ok_or_else(|| "tmux stdin unavailable".to_string())
        .and_then(|stdin| {
            stdin
                .write_all(input)
                .map_err(|e| format!("tmux stdin failed: {e}"))
        });
    drop(child.stdin.take());
    if let Err(error) = write_result {
        let _ = child.wait();
        return Err(error);
    }
    let out = child
        .wait_with_output()
        .map_err(|e| format!("tmux wait failed: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "tmux {} failed: {}",
            args.first().unwrap_or(&""),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// Owned-argument variant used for bounded command batches whose numeric
/// cursor movements are assembled at runtime. Arguments still bypass a
/// shell; `;` is an explicit tmux command separator, never shell syntax.
pub(crate) fn tmux_owned(args: &[String]) -> Result<String, String> {
    let conf = tmux_conf();
    let out = Command::new(tmux_bin())
        .args(["-f", &conf, "-L", socket()])
        .args(args)
        .env("LANG", "en_US.UTF-8")
        .output()
        .map_err(|e| format!("tmux not runnable: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "tmux {} failed: {}",
            args.first().map(String::as_str).unwrap_or(""),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// Run a `;`-separated tmux command batch, returning stdout even when one
/// command in the batch fails (e.g. a session died between listing and
/// capture). Callers parse per-command markers, so partial output is useful
/// and a hard error would throw away every other command's result.
pub(crate) fn tmux_batch(args: &[String]) -> String {
    let conf = tmux_conf();
    Command::new(tmux_bin())
        .args(["-f", &conf, "-L", socket()])
        .args(args)
        .env("LANG", "en_US.UTF-8") // see tmux(): C locale mangles output
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
        .unwrap_or_default()
}

/// One tmux.conf line exporting this instance's status-socket path into the
/// server environment (see agent_status.rs). A path tmux's double-quoted
/// string could misread is skipped — the helper then uses its production
/// default, which is only wrong for exotic isolated data dirs.
pub(crate) fn status_sock_env_line(deck_dir: &std::path::Path) -> String {
    let sock = deck_dir.join("status.sock").display().to_string();
    if sock.contains(['"', '\\', '\n', '#', '$', '`']) {
        return String::new();
    }
    format!("set-environment -g DECK_STATUS_SOCK \"{sock}\"\n")
}

/// Escape a string for use inside a tmux format/message argument:
/// `#` starts a format expansion in `display-message -p`.
pub(crate) fn fmt_escape(s: &str) -> String {
    s.replace('#', "##")
}

/// Session names reach tmux CLI arguments, format strings, and log lines, so
/// the accepted alphabet is the intersection of what tmux allows (no `:` `.`)
/// and what can never read as a flag (no leading `-`) or a format expansion
/// (no `#`). deck itself only generates `deck-<a-z0-9-slug>-<id>`.
pub(crate) fn validate_session_name(name: &str) -> Result<(), String> {
    if name.is_empty() || name.len() > 64 {
        return Err("session name must be 1–64 characters".into());
    }
    if name.starts_with('-') {
        return Err("session name must not start with '-'".into());
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '@'))
    {
        return Err("session name may only contain letters, digits, _ - @".into());
    }
    Ok(())
}

/// Exact-match session target. Pane-level commands need the trailing colon.
pub(crate) fn session_target(name: &str) -> String {
    format!("={name}")
}
pub(crate) fn pane_target(name: &str) -> String {
    format!("={name}:")
}

pub(crate) fn expand_tilde(path: &str) -> String {
    if let Some(rest) = path.strip_prefix('~') {
        if let Some(home) = dirs::home_dir() {
            return format!("{}{}", home.display(), rest);
        }
    }
    path.to_string()
}

// ---------- session lifecycle ------------------------------------------------

/// Start a detached session: login shell in `dir`, then type `cmd` into it,
pub(crate) fn init_deck_server() {
    // config file covers fresh servers; these cover an ALREADY RUNNING
    // server (e.g. started by an older deck before an update)
    let _ = tmux(&["set-environment", "-g", "COLORTERM", "truecolor"]);
    // Panes tell the status helper (agent_status.rs) which instance's socket
    // to write to, so an isolated/smoke instance receives its own events.
    let sock = crate::datadir::deck_dir().join("status.sock");
    let _ = tmux(&[
        "set-environment",
        "-g",
        "DECK_STATUS_SOCK",
        &sock.display().to_string(),
    ]);
    let _ = tmux(&["set", "-g", "status", "off"]);
    let _ = tmux(&["set", "-g", "mouse", "off"]);
    let _ = tmux(&["set", "-g", "set-clipboard", "on"]);
    let _ = tmux(&["set", "-g", "history-limit", "50000"]);
    // Deck paints selection geometry in one DOM layer after each settled
    // backend update. Hiding tmux's transient selection prevents its
    // top-line/cursor motion steps from flashing large history regions.
    // Keep mode-style empty as the compatibility fallback while the bundled
    // tmux exposes separate selection and position styles.
    let _ = tmux(&["set", "-g", "mode-style", "none"]);
    let _ = tmux(&["set", "-g", "copy-mode-selection-style", "none"]);
    let _ = tmux(&["set", "-g", "copy-mode-position-style", "reverse"]);
    let _ = tmux(&["set", "-g", "copy-mode-position-format", ""]);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_names_accept_the_deck_alphabet() {
        for ok in ["deck-my-card-ab12", "elemental-tcg-02", "a", "A_b@2"] {
            assert!(validate_session_name(ok).is_ok(), "{ok}");
        }
    }

    #[test]
    fn session_names_reject_flags_formats_and_separators() {
        for bad in [
            "",             // empty
            "-starts-dash", // reads as a flag
            "has space",
            "has:colon", // tmux target separator
            "has.dot",   // tmux target separator
            "has#hash",  // tmux format expansion
            "has;semi",
            "日本語", // outside the generated alphabet
            &"x".repeat(65),
        ] {
            assert!(validate_session_name(bad).is_err(), "{bad:?}");
        }
    }

    #[test]
    fn server_defaults_keep_selection_frames_invisible_and_status_off() {
        let conf = tmux_conf_text(std::path::Path::new("/tmp/deck"));
        for line in [
            "set -g status off",
            "set -g history-limit 50000",
            "set -g mode-style 'none'",
            "set -g copy-mode-selection-style 'none'",
            "set -g copy-mode-position-style 'reverse'",
            "set-environment -g DECK_STATUS_SOCK \"/tmp/deck/status.sock\"",
        ] {
            assert!(
                conf.lines().any(|l| l == line),
                "missing server default: {line}"
            );
        }
    }

    #[test]
    fn status_sock_env_line_is_quoted_or_omitted() {
        assert_eq!(
            status_sock_env_line(std::path::Path::new("/tmp/deck test")),
            "set-environment -g DECK_STATUS_SOCK \"/tmp/deck test/status.sock\"\n"
        );
        // a path tmux's double-quoted string could misread is omitted, not mangled
        assert_eq!(
            status_sock_env_line(std::path::Path::new("/tmp/de\"ck")),
            ""
        );
        assert_eq!(status_sock_env_line(std::path::Path::new("/tmp/de$ck")), "");
    }

    #[test]
    fn fmt_escape_doubles_hashes() {
        assert_eq!(fmt_escape("a#b##c"), "a##b####c");
        assert_eq!(fmt_escape("plain"), "plain");
    }

    #[test]
    fn production_and_debug_socket_names_are_reserved() {
        assert_ne!("deck", "deck-dev");
        assert!("deck-smoke-123".starts_with("deck-smoke"));
    }

    #[test]
    fn binary_kinds_targets_socket_and_paths_are_classified_without_guessing() {
        assert_eq!(tmux_kind_of("tmux"), "PATH");
        assert_eq!(tmux_kind_of("/opt/homebrew/bin/tmux"), "homebrew");
        assert_eq!(tmux_kind_of("/usr/local/bin/tmux"), "homebrew");
        assert_eq!(tmux_kind_of("/opt/local/bin/tmux"), "macports");
        assert_eq!(
            tmux_kind_of("/Applications/deck.app/Contents/MacOS/tmux"),
            "sidecar"
        );

        assert_eq!(session_target("deck-card-ab12"), "=deck-card-ab12");
        assert_eq!(pane_target("deck-card-ab12"), "=deck-card-ab12:");
        assert_eq!(expand_tilde("/tmp/project"), "/tmp/project");
        assert!(expand_tilde("~/project").ends_with("/project"));
        assert_eq!(socket(), "deck-dev");
        let binary = tmux_bin();
        assert!(!binary.is_empty());
        assert_eq!(tmux_kind(), tmux_kind_of(binary));
    }
}
