//! tmux backend: sidecar discovery, the private `deck` server, config, and
//! raw command execution. Everything deck knows about tmux lives here.

use std::path::PathBuf;
use std::process::Command;

use crate::applog;

// ---------- tmux helpers ----------------------------------------------------

/// Absolute path to tmux. The bundled sidecar comes first (zero-dependency
/// installs — a statically linked tmux ships inside the .app); Homebrew /
/// MacPorts are fallbacks for source builds. Apps launched from Finder get
/// launchd's PATH (no /opt/homebrew/bin), so plain "tmux" is last resort.
pub(crate) fn tmux_bin() -> &'static str {
    static BIN: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    BIN.get_or_init(|| {
        let mut candidates: Vec<String> = Vec::new();
        if let Ok(exe) = std::env::current_exe() {
            if let Some(dir) = exe.parent() {
                candidates.push(dir.join("tmux").display().to_string());
            }
        }
        for p in [
            "/opt/homebrew/bin/tmux",
            "/usr/local/bin/tmux",
            "/opt/local/bin/tmux",
        ] {
            candidates.push(p.to_string());
        }
        for c in candidates {
            if std::path::Path::new(&c).exists() {
                applog(&format!("[tmux] using {c}"));
                return c;
            }
        }
        applog("[tmux] falling back to PATH lookup");
        "tmux".to_string()
    })
}

/// deck runs its own tmux server (socket "deck"): the bundled binary never
/// clashes with a user-installed tmux of a different version, and deck's
/// sessions stay out of the user's personal `tmux ls`.
pub(crate) const SOCKET: &str = "deck";

/// Server config file: options set via `tmux set -g` die with the server
/// process (a session-less server exits immediately, so boot-time `set`
/// calls raced server restarts and the status bar kept coming back).
/// A -f config is applied at every server spawn, deterministically.
pub(crate) fn tmux_conf() -> String {
    static CONF: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    CONF.get_or_init(|| {
        let path = dirs::home_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join(".deck")
            .join("tmux.conf");
        if let Some(dir) = path.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        let _ = std::fs::write(
            &path,
            "# generated by deck — server defaults\n\
             set -g status off\n\
             set -g set-clipboard on\n\
             set -g history-limit 50000\n\
             set -g copy-mode-position-format ''\n\
             set-environment -g COLORTERM truecolor\n",
        );
        path.display().to_string()
    })
    .clone()
}

/// Run tmux (on the deck server) with output captured — stray stderr must
/// never reach a terminal.
pub(crate) fn tmux(args: &[&str]) -> Result<String, String> {
    let conf = tmux_conf();
    let out = Command::new(tmux_bin())
        .args(["-f", &conf, "-L", SOCKET])
        .args(args)
        .output()
        .map_err(|e| format!("tmux not runnable: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "tmux {} failed: {}",
            args.first().unwrap_or(&""),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// Exact-match session target. Pane-level commands need the trailing colon.
pub(crate) fn session_target(name: &str) -> String {
    format!("={name}")
}
pub(crate) fn pane_target(name: &str) -> String {
    format!("={name}:")
}

pub(crate) fn expand_tilde(path: &str) -> String {
    if let Some(rest) = path.strip_prefix('~') {
        if let Some(home) = dirs::home_dir() {
            return format!("{}{}", home.display(), rest);
        }
    }
    path.to_string()
}

// ---------- session lifecycle ------------------------------------------------

/// Start a detached session: login shell in `dir`, then type `cmd` into it,
pub(crate) fn init_deck_server() {
    // config file covers fresh servers; these cover an ALREADY RUNNING
    // server (e.g. started by an older deck before an update)
    let _ = tmux(&["set-environment", "-g", "COLORTERM", "truecolor"]);
    let _ = tmux(&["set", "-g", "status", "off"]);
    let _ = tmux(&["set", "-g", "mouse", "off"]);
    let _ = tmux(&["set", "-g", "set-clipboard", "on"]);
    let _ = tmux(&["set", "-g", "history-limit", "50000"]);
    let _ = tmux(&["set", "-g", "copy-mode-position-format", ""]);
}
