#!/usr/bin/env python3
"""Deck Controlled Execution calibration harness: Terminal vs Full Local evidence.

Records OBSERVATIONS for the cases of one frozen plan (scripts/ce/plan-*.json);
it never classifies. The one authority that turns evidence into a verdict is
scripts/ce_verdict.py.

Two modes, never mixed in one evidence file:

`ci` (default) — deterministic. One disposable bundled-tmux server
(`-S <private dir>/t.sock`, Deck's server defaults from
`tmux::tmux_conf_text`) started with a SYNTHETIC session environment: a
synthetic HOME with synthetic zsh startup files and toolchain shims, a
synthetic ssh-agent socket, a synthetic developer variable, and a session
PATH with one synthetic base directory. Nothing from the invoking shell's
environment is passed on.

`designated` — the real user environment, run only with maintainer approval.
It attaches to the tmux server of an ISOLATED smoke Deck (`--smoke-socket
deck-smoke-…`, launched by `app/run.sh` with `DECK_SMOKE_DATA_DIR`) and
refuses to start a server itself: the server must carry Deck's
`@deck-server-metadata`, so its environment is the one Deck gave it. It
creates only its own sessions (`ce-*`) in a disposable project directory,
uses the real login shell and startup files, records environment variables by
PRESENCE only, executable identities as path class + SHA-256 prefix
(`probe.zsh --hashed`), the ssh-agent by socket reachability only, and a
random synthetic sentinel in the real HOME that is deleted afterwards.

Lanes (plan names):
- A1 / A2: a session created the ORDINARY way (no command → tmux's own
  login interactive shell, as an ordinary Deck card); the probe is typed.
- A1-base / A2-base: the probe as a pane process started directly by the
  same server — what any program in the session gets without startup files.
- B-direct / B2-direct: the real `deck-mcp-runner` as a pane process of the
  same server (as an MCP card). This process plays Deck: it is the
  `--deck-pid`, claims the runner key through the kernel-checked bootstrap,
  takes MCP control, authorizes one grant and dispatches the probe as a
  structured direct launch.
- B-login: the same runner, `/bin/zsh -lc` (plan v1 only).
- B-shell / B2-shell: the same runner, `/bin/zsh -lic` — the candidate
  Terminal-semantic invocation. Its records also carry `invocation` metadata
  (exit code, duration, output byte count; never the output).
- B-admission (`--app-probe`, ci only): the deck-app test `ce1_probe_*`
  records how the production `deck_exec` route admits a Full Local cwd.

Cleanup is evidence (`cleanup`): ci kills its server and removes its
directory; designated kills only the sessions it created, removes its
directory and the HOME sentinel, and confirms each. The smoke Deck and its
server are the operator's to stop afterwards (`scripts/edr_runtime.py
--cleanup --socket …`). No secret, Keychain item, business repository or
credentialed network destination is touched.

  scripts/ce_parity.py --plan scripts/ce/plan-full-local-2.json --out ci.jsonl --app-probe
  scripts/ce_parity.py --plan scripts/ce/plan-full-local-2.json --mode designated \\
      --smoke-socket deck-smoke-ce --runner <smoke bundle>/deck-mcp-runner --out d.jsonl

Exit status: 0 when every planned observation of the mode was recorded
(whatever it shows) and cleanup was confirmed; 1 otherwise; 2 on usage errors.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parent.parent
PROBE = REPOSITORY / "scripts" / "ce" / "probe.zsh"
TAURI = REPOSITORY / "app" / "src-tauri"
TMUX = TAURI / "binaries" / "tmux-aarch64-apple-darwin"
RUNNER = TAURI / "target" / "debug" / "deck-mcp-runner"
EVIDENCE_SCHEMA = "deck-ce-evidence/1"
SERVICE = "svc_ce"
GENERATION = "g_ce"
HOLDER = "holder_ce"
GRANT = "grant_ce"
POLICY_VERSION = 2
LANES = {
    "ci": ("A1", "A1-base", "B-direct", "B-login", "B-shell"),
    "designated": ("A2", "A2-base", "B2-direct", "B2-shell"),
}
TERMINAL, BASE, DIRECT, LOGIN, SHELL = "terminal", "base", "direct", "login", "shell"
LANE_KIND = {
    "A1": TERMINAL, "A2": TERMINAL, "A1-base": BASE, "A2-base": BASE,
    "B-direct": DIRECT, "B2-direct": DIRECT, "B-login": LOGIN, "B-shell": SHELL, "B2-shell": SHELL,
}
PROBE_TIMEOUT = 30.0
SESSION_PATH = "/usr/bin:/bin:/usr/sbin:/sbin"

# Deck's tmux server defaults (tmux::tmux_conf_text); DECK_STATUS_SOCK names
# a synthetic path here, with no listener.
DECK_TMUX_CONF = """# generated by deck — server defaults
set -g status off
set -g mouse on
set -g set-clipboard off
set -g history-limit 50000
set -g mode-style 'none'
set -g copy-mode-selection-style 'none'
set -g copy-mode-position-style 'reverse'
set -g copy-mode-position-format ''
set-environment -g COLORTERM truecolor
set-environment -g DECK_STATUS_SOCK "{status_sock}"
"""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def plan_digest(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def private_dir(prefix: str) -> Path:
    root = Path(tempfile.mkdtemp(prefix=prefix, dir="/tmp"))
    os.chmod(root, 0o700)
    return root


class Fixture:
    """The synthetic world of the ci mode."""

    def __init__(self, root: Path):
        self.root = root
        self.home = root / "home"
        self.tools = root / "tools"
        self.project = root / "project"
        self.outside = root / "outside"
        self.tmp = root / "tmp"
        self.out = root / "out"
        self.tmux_socket = root / "t.sock"
        self.runner_socket = root / "r.sock"
        self.agent_socket = root / "agent.sock"
        self.unix_socket = root / "u.sock"
        self.status_socket = root / "status.sock"
        self.conf = root / "tmux.conf"
        self.ready = root / "a-ready"
        self.outside_file = self.outside / "sentinel.txt"
        self.outside_token = "ce-outside-" + os.urandom(6).hex()
        self.tcp_token = "ce-tcp-" + os.urandom(6).hex()
        self.unix_token = "ce-unix-" + os.urandom(6).hex()
        self.tcp_port = 0
        self.base_bin = self.tools / "base-bin"

    def build(self) -> None:
        for directory in (self.home, self.project, self.outside, self.tmp, self.out):
            directory.mkdir(mode=0o700)
        roots = {name: self.tools / name for name in ("base-bin", "env-bin", "login-bin", "rc-bin", "shadow-login", "shadow-rc")}
        for directory in roots.values():
            directory.mkdir(mode=0o700, parents=True)

        def shim(path: Path, text: str) -> None:
            path.write_text(text)
            path.chmod(0o755)

        def tool(directory: Path, name: str, version: str) -> None:
            shim(directory / name, f"#!/bin/zsh -f\nprint -r -- {shlex.quote(name + ' ' + version)}\n")

        tool(roots["base-bin"], "ce-tool-base", "1.0.0-session")
        tool(roots["base-bin"], "ce-base-interp", "1.0.0-session")
        shim(roots["base-bin"] / "ce-base-launcher", "#!/usr/bin/env ce-base-interp\n")
        tool(roots["env-bin"], "ce-tool-env", "1.0.0")
        tool(roots["login-bin"], "ce-tool-login", "1.0.0")
        tool(roots["rc-bin"], "ce-tool-rc", "1.0.0")
        tool(roots["shadow-login"], "ce-tool-shadow", "1.0.0-login")
        tool(roots["shadow-rc"], "ce-tool-shadow", "2.0.0-interactive")
        tool(roots["shadow-login"], "ce-interp", "1.0.0-login")
        tool(roots["shadow-rc"], "ce-interp", "2.0.0-interactive")
        shim(roots["env-bin"] / "ce-launcher", "#!/usr/bin/env ce-interp\n")

        (self.home / ".zshenv").write_text(f'export PATH="{roots["env-bin"]}:$PATH"\n')
        (self.home / ".zprofile").write_text(f'export PATH="{roots["shadow-login"]}:{roots["login-bin"]}:$PATH"\n')
        (self.home / ".zshrc").write_text(
            f'export PATH="{roots["shadow-rc"]}:{roots["rc-bin"]}:$PATH"\n'
            "PS1='ce%# '\n"
            f"[[ -o login ]] && [[ -t 0 ]] && print -r ready > {shlex.quote(str(self.ready))}\n"
        )
        (self.home / ".gitconfig").write_text(
            "[user]\n\tname = CE Probe\n\temail = ce-probe@example.invalid\n[init]\n\tdefaultBranch = main\n"
        )
        self.outside_file.write_text(self.outside_token)
        self.conf.write_text(DECK_TMUX_CONF.format(status_sock=self.status_socket))

    def environment(self) -> dict[str, str]:
        """The synthetic session environment (a stand-in for the GUI session)."""
        user = os.environ.get("USER") or os.environ.get("LOGNAME") or "ce"
        return {
            "HOME": str(self.home),
            "USER": user,
            "LOGNAME": user,
            "SHELL": "/bin/zsh",
            "TMPDIR": str(self.tmp) + "/",
            "PATH": f"{self.base_bin}:{SESSION_PATH}",
            "LANG": "en_US.UTF-8",
            "SSH_AUTH_SOCK": str(self.agent_socket),
            "CE_DEV_VAR": "ce-synthetic-developer-value",
        }

    def substitutions(self) -> dict[str, str]:
        return {
            "{outside_file}": str(self.outside_file),
            "{outside_token}": self.outside_token,
            "{outside_dir}": str(self.outside),
            "{tcp_port}": str(self.tcp_port),
            "{tcp_token}": self.tcp_token,
            "{unix_path}": str(self.unix_socket),
            "{unix_token}": self.unix_token,
            "{base_launcher}": str(self.base_bin / "ce-base-launcher"),
        }


class Servers:
    """Synthetic localhost TCP, Unix-socket and ssh-agent-like listeners (ci)."""

    def __init__(self, fixture: Fixture):
        self.fixture = fixture
        self.stop = threading.Event()
        self.sockets: list[socket.socket] = []

    def start(self) -> None:
        tcp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        tcp.bind(("127.0.0.1", 0))
        tcp.listen(8)
        self.fixture.tcp_port = tcp.getsockname()[1]
        unix = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        unix.bind(str(self.fixture.unix_socket))
        unix.listen(8)
        agent = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        agent.bind(str(self.fixture.agent_socket))
        agent.listen(8)
        self.sockets = [tcp, unix, agent]
        for listener, handler in (
            (tcp, lambda conn: conn.sendall(self.fixture.tcp_token.encode() + b"\n")),
            (unix, lambda conn: conn.sendall(self.fixture.unix_token.encode() + b"\n")),
            (agent, self.agent),
        ):
            threading.Thread(target=self.serve, args=(listener, handler), daemon=True).start()

    def serve(self, listener: socket.socket, handler) -> None:
        listener.settimeout(0.2)
        while not self.stop.is_set():
            try:
                conn, _ = listener.accept()
            except (socket.timeout, OSError):
                continue
            with conn:
                conn.settimeout(2)
                try:
                    handler(conn)
                except OSError:
                    pass

    @staticmethod
    def agent(conn: socket.socket) -> None:
        """Minimal agent: REQUEST_IDENTITIES (11) → IDENTITIES_ANSWER (12), zero keys."""
        while True:
            header = conn.recv(4)
            if len(header) < 4:
                return
            length = int.from_bytes(header, "big")
            body = b""
            while len(body) < length:
                chunk = conn.recv(length - len(body))
                if not chunk:
                    return
                body += chunk
            if body[:1] == b"\x0b":
                conn.sendall((5).to_bytes(4, "big") + b"\x0c" + (0).to_bytes(4, "big"))
            else:
                conn.sendall((1).to_bytes(4, "big") + b"\x05")

    def close(self) -> bool:
        self.stop.set()
        for listener in self.sockets:
            listener.close()
        return True


class Tmux:
    def __init__(self, server_args: list[str], environment: dict[str, str]):
        self.server_args = server_args
        self.environment = environment

    def run(self, *args: str, check: bool = True) -> str:
        result = subprocess.run(
            [str(TMUX), *self.server_args, *args],
            env=self.environment, capture_output=True, text=True, timeout=15,
        )
        if check and result.returncode != 0:
            raise RuntimeError(f"tmux {args[0]} failed")
        return result.stdout


class Runner:
    """This process plays Deck toward one runner pane."""

    def __init__(self, socket_path: Path):
        self.socket_path = socket_path
        self.key = ""
        self.sequence = 0
        self.grant_authorizations = 0

    def raw(self, request: dict) -> dict:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as connection:
            connection.settimeout(10)
            connection.connect(str(self.socket_path))
            connection.sendall(json.dumps(request).encode() + b"\n")
            data = b""
            while not data.endswith(b"\n"):
                chunk = connection.recv(65536)
                if not chunk:
                    break
                data += chunk
        return json.loads(data)

    def call(self, request: dict) -> dict:
        return self.raw({**request, "auth": self.key})

    def claim_control_and_grant(self) -> None:
        claim = self.raw({"kind": "claim", "service_instance": SERVICE, "generation": GENERATION})
        self.key = claim["auth"]
        control = self.call({"kind": "control", "mode": "mcp", "service_instance": SERVICE, "control_epoch": 1, "holder_id": HOLDER})
        if control.get("ok") is not True:
            raise RuntimeError("runner refused MCP control")
        grant = self.call({
            "kind": "authorize-grant", "service_instance": SERVICE, "grant_id": GRANT,
            "grant_version": 1, "policy_version": POLICY_VERSION, "expires_at": 2**63 - 1,
        })
        if grant.get("ok") is not True:
            raise RuntimeError("runner refused the grant")
        self.grant_authorizations += 1

    def exec_and_wait(self, executable: str, args: list[str], cwd: str) -> tuple[str, dict]:
        self.sequence += 1
        job = f"job_ce_{self.sequence}"
        context = {
            "service_instance": SERVICE, "holder_id": HOLDER, "control_epoch": 1,
            "grant_id": GRANT, "grant_version": 1, "policy_version": POLICY_VERSION,
            "intent_hash": f"{self.sequence:064x}", "expires_at": 2**63 - 1,
        }
        started = self.call({
            "kind": "exec", "job_id": job, "request_hash": f"hash_ce_{self.sequence}",
            "executable": executable, "args": args, "cwd": cwd, "wait_ms": 0,
            "timeout_ms": int(PROBE_TIMEOUT * 1000), "context": context,
        })
        if started.get("ok") is not True:
            return "runner-rejected:" + str(started.get("error", "unknown")), {}
        limit = time.monotonic() + PROBE_TIMEOUT + 5
        while time.monotonic() < limit:
            read = self.call({"kind": "read", "job_id": job, "cursor": 0, "max_bytes": 1, "wait_ms": 200})
            state = read.get("job", {})
            if state.get("state") not in ("running", "starting") and state.get("outputComplete") is True:
                return "completed", state
        return "job-timeout", {}


def wait_for(path: Path, timeout: float) -> bool:
    limit = time.monotonic() + timeout
    while time.monotonic() < limit:
        if path.exists():
            return True
        time.sleep(0.05)
    return False


def resolve(tokens: list[str], substitutions: dict[str, str]) -> list[str]:
    return [substitutions.get(token, token) for token in tokens]


def read_observation(path: Path) -> tuple[dict | None, str | None]:
    if not path.exists():
        return None, "no-observation"
    try:
        value = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None, "malformed-observation"
    if not isinstance(value, dict) or value.get("kind") == "error":
        return None, "probe-error"
    return value, None


def server_answers(path: Path) -> bool:
    if not path.exists():
        return False
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as probe:
        try:
            probe.connect(str(path))
        except OSError:
            return False
    return True


def pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


class Lanes:
    """Runs one probe in one lane of an already prepared server."""

    def __init__(self, tmux: Tmux, runner: Runner, out_dir: Path, project: Path, probe_flags: list[str]):
        self.tmux = tmux
        self.runner = runner
        self.out_dir = out_dir
        self.project = project
        self.probe_flags = probe_flags
        self.sequence = 0
        self.base_sessions: list[str] = []

    def command(self, out: Path, probe_args: list[str]) -> list[str]:
        return [str(PROBE), *self.probe_flags, str(out), *probe_args]

    def observe(self, lane: str, probe_args: list[str], a_cwd: str | None) -> dict:
        self.sequence += 1
        out = self.out_dir / f"obs-{self.sequence}.json"
        record: dict = {}
        kind = LANE_KIND[lane]
        argv = self.command(out, probe_args)
        if kind == TERMINAL:
            cwd = a_cwd or str(self.project)
            self.tmux.run("send-keys", "-t", "=ce-term:", "-l", "--", f"cd {shlex.quote(cwd)} && {shlex.join(argv)}")
            self.tmux.run("send-keys", "-t", "=ce-term:", "Enter")
            wait_for(out, PROBE_TIMEOUT)
        elif kind == BASE:
            name = f"ce-base-{self.sequence}"
            self.base_sessions.append(name)
            self.tmux.run("new-session", "-d", "-s", name, "-c", str(self.project), *argv)
            wait_for(out, PROBE_TIMEOUT)
        else:
            if kind == DIRECT:
                executable, args = argv[0], argv[1:]
            else:
                executable, args = "/bin/zsh", ["-lc" if kind == LOGIN else "-lic", "exec " + shlex.join(argv)]
            started = time.monotonic()
            status, state = self.runner.exec_and_wait(executable, args, str(self.project))
            if status != "completed":
                record["error"] = status
            if kind == SHELL:
                record["invocation"] = {
                    "status": status, "exit_code": state.get("exitCode"),
                    "termination_signal": state.get("terminationSignal"),
                    "duration_ms": int((time.monotonic() - started) * 1000),
                    "output_bytes": state.get("endCursor"),
                }
        if "error" not in record:
            observation, error = read_observation(out)
            if error:
                record["error"] = error
            else:
                record["observation"] = observation
        return record


def start_runner(tmux: Tmux, runner_binary: Path, socket_path: Path, cwd: Path) -> Runner:
    tmux.run(
        "new-session", "-d", "-s", "ce-mcp", "-c", str(cwd), str(runner_binary),
        "--socket", str(socket_path), "--generation", GENERATION,
        "--service-instance", SERVICE, "--deck-pid", str(os.getpid()),
        "--output-retention-ms", "60000",
    )
    if not wait_for(socket_path, 10):
        raise RuntimeError("the runner socket never appeared")
    runner = Runner(socket_path)
    runner.claim_control_and_grant()
    return runner


def pane_pids(tmux: Tmux, sessions: list[str]) -> list[int]:
    pids = []
    for name in sessions:
        text = tmux.run("list-panes", "-t", f"={name}", "-F", "#{pane_pid}", check=False)
        pids += [int(pid) for pid in text.split() if pid.isdigit()]
    return pids


def run_cases(lanes: Lanes, cases: list[dict], mode_lanes: tuple[str, ...], substitutions: dict[str, str], records: list[dict]) -> bool:
    complete = True
    for case in cases:
        probe_args = resolve(case["probe"], substitutions)
        a_cwd = resolve([case["a_cwd"]], substitutions)[0] if "a_cwd" in case else None
        for lane in case["lanes"]:
            if lane not in mode_lanes:
                continue
            record = {"kind": "observation", "case": case["id"], "lane": lane, **lanes.observe(lane, probe_args, a_cwd)}
            complete &= "error" not in record
            records.append(record)
    return complete


def header(plan: dict, digest: str, env: str, lanes: list[str], args, runner_binary: Path) -> dict:
    return {
        "kind": "run", "schema": EVIDENCE_SCHEMA, "plan": plan["id"], "plan_digest": digest,
        "evidence_env": env, "lanes": lanes, "deck_build": args.deck_build,
        "runner_build": "sha256:" + sha256_file(runner_binary),
        "tmux_build": "sha256:" + sha256_file(TMUX), "probe_build": "sha256:" + sha256_file(PROBE),
        "started_at_ms": int(time.time() * 1000),
    }


def friction(runner: Runner | None) -> dict:
    return {
        "kind": "friction", "lane": "B", "scope": "runner-protocol", "initial_approvals": 1,
        "additional_prompts": (runner.grant_authorizations - 1) if runner else None,
        "manual_recovery": 0,
        "note": "UI prompt counts need a UI lane; this counts grant re-authorizations the harness needed",
    }


def run_ci(args, plan, digest, runner_binary: Path) -> tuple[list[dict], bool]:
    cases = [case for case in plan["cases"] if case["evidence_env"] == "ci"]
    used = sorted({lane for case in cases for lane in case["lanes"] if lane in LANES["ci"]})
    root = private_dir("dce-")
    fixture = Fixture(root)
    records = [header(plan, digest, "ci", used, args, runner_binary)]
    servers = Servers(fixture)
    tmux = None
    runner = None
    pids: list[int] = []
    complete = True
    try:
        fixture.build()
        servers.start()
        tmux = Tmux(["-f", str(fixture.conf), "-S", str(fixture.tmux_socket)], fixture.environment())
        tmux.run("new-session", "-d", "-s", "ce-term", "-c", str(fixture.project))
        if not wait_for(fixture.ready, 10):
            raise RuntimeError("the A1 terminal shell never became interactive")
        runner = start_runner(tmux, runner_binary, fixture.runner_socket, fixture.project)
        pids = pane_pids(tmux, ["ce-term", "ce-mcp"])
        lanes = Lanes(tmux, runner, fixture.out, fixture.project, [])
        complete = run_cases(lanes, cases, LANES["ci"], fixture.substitutions(), records)
        records.append(friction(runner))
    except Exception as error:  # the run itself failed: record it, never a pass
        records.append({"kind": "run-error", "error": type(error).__name__, "detail": str(error)[:200]})
        complete = False
    finally:
        server_gone = True
        if tmux is not None:
            tmux.run("kill-server", check=False)
            limit = time.monotonic() + 5
            while time.monotonic() < limit and (server_answers(fixture.tmux_socket) or any(pid_alive(pid) for pid in pids)):
                time.sleep(0.05)
            # tmux leaves its socket file behind; a refused connection is the proof.
            server_gone = not server_answers(fixture.tmux_socket)
        panes_gone = not any(pid_alive(pid) for pid in pids)
        for pid in pids:
            if pid_alive(pid):
                try:
                    os.kill(pid, signal.SIGKILL)
                except OSError:
                    pass
        listeners_closed = servers.close()
        shutil.rmtree(root, ignore_errors=True)
        records.append({
            "kind": "cleanup", "tmux_server_gone": server_gone, "pane_processes_gone": panes_gone,
            "listeners_closed": listeners_closed, "work_dir_removed": not root.exists(),
        })
        complete &= server_gone and panes_gone and not root.exists()
    return records, complete


def run_designated(args, plan, digest, runner_binary: Path) -> tuple[list[dict], bool]:
    if not args.smoke_socket or not args.smoke_socket.startswith("deck-smoke"):
        raise SystemExit("designated mode needs --smoke-socket deck-smoke-… (an isolated smoke Deck)")
    cases = [case for case in plan["cases"] if case["evidence_env"] == "designated"]
    used = sorted({lane for case in cases for lane in case["lanes"] if lane in LANES["designated"]})
    home = Path(os.path.expanduser("~"))
    probe_env = {"PATH": SESSION_PATH, "LANG": "en_US.UTF-8", "HOME": str(home)}
    preflight = Tmux(["-L", args.smoke_socket], probe_env)
    metadata = preflight.run("show-options", "-gv", "@deck-server-metadata", check=False).strip()
    if not metadata:
        raise SystemExit("the smoke server is absent or not started by Deck (no @deck-server-metadata); refusing")
    # tmux copies update-environment variables from each client into a new
    # session; use the server's own value so our client changes nothing.
    client_env = dict(probe_env)
    agent = preflight.run("show-environment", "-g", "SSH_AUTH_SOCK", check=False).strip()
    if agent.startswith("SSH_AUTH_SOCK="):
        client_env["SSH_AUTH_SOCK"] = agent.split("=", 1)[1]
    tmux = Tmux(["-L", args.smoke_socket], client_env)
    del agent

    root = private_dir("dce-d-")
    project = root / "project"
    out = root / "out"
    project.mkdir(mode=0o700)
    out.mkdir(mode=0o700)
    sentinel = home / f".deck-ce-sentinel-{os.urandom(8).hex()}"
    token = "ce-home-" + os.urandom(12).hex()
    records = [header(plan, digest, "designated", used, args, runner_binary)]
    runner = None
    lanes = None
    created: list[str] = []
    pids: list[int] = []
    complete = True
    try:
        fd = os.open(sentinel, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(token)
        created.append("ce-term")
        ready = root / "a-ready"
        tmux.run("new-session", "-d", "-s", "ce-term", "-c", str(project))
        limit = time.monotonic() + 60
        while not ready.exists() and time.monotonic() < limit:
            # `fc -p` gives this shell an in-memory history, so the probe
            # commands never reach the user's history file.
            tmux.run("send-keys", "-t", "=ce-term:", "-l", "--", f"fc -p; : > {shlex.quote(str(ready))}")
            tmux.run("send-keys", "-t", "=ce-term:", "Enter")
            wait_for(ready, 3)
        if not ready.exists():
            raise RuntimeError("the A2 terminal shell never became interactive")
        created.append("ce-mcp")
        runner = start_runner(tmux, runner_binary, root / "r.sock", project)
        pids = pane_pids(tmux, ["ce-term", "ce-mcp"])
        lanes = Lanes(tmux, runner, out, project, ["--hashed"])
        substitutions = {"{home_sentinel}": str(sentinel), "{home_token}": token}
        complete = run_cases(lanes, cases, LANES["designated"], substitutions, records)
        records.append(friction(runner))
    except Exception as error:
        records.append({"kind": "run-error", "error": type(error).__name__, "detail": str(error)[:200]})
        complete = False
    finally:
        sessions = created + (lanes.base_sessions if lanes else [])
        for name in sessions:
            tmux.run("kill-session", "-t", f"={name}", check=False)
        limit = time.monotonic() + 5
        while time.monotonic() < limit and any(pid_alive(pid) for pid in pids):
            time.sleep(0.05)
        remaining = tmux.run("list-sessions", "-F", "#{session_name}", check=False).split()
        sessions_gone = not any(name in remaining for name in sessions)
        panes_gone = not any(pid_alive(pid) for pid in pids)
        sentinel.unlink(missing_ok=True)
        shutil.rmtree(root, ignore_errors=True)
        records.append({
            "kind": "cleanup", "harness_sessions_gone": sessions_gone, "pane_processes_gone": panes_gone,
            "home_sentinel_removed": not sentinel.exists(), "work_dir_removed": not root.exists(),
        })
        complete &= sessions_gone and panes_gone and not sentinel.exists() and not root.exists()
    return records, complete


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--plan", required=True, type=Path, help="frozen plan (scripts/ce/plan-*.json)")
    parser.add_argument("--out", required=True, help="evidence JSONL to write")
    parser.add_argument("--mode", choices=("ci", "designated"), default="ci")
    parser.add_argument("--runner", default=str(RUNNER), help="deck-mcp-runner binary (default: debug build)")
    parser.add_argument("--smoke-socket", help="designated: the isolated smoke Deck tmux socket label")
    parser.add_argument("--app-probe", action="store_true", help="ci: also record the deck_exec cwd admission (B-admission)")
    parser.add_argument("--deck-build", default="unknown", help="commit the evidence describes")
    args = parser.parse_args(argv)

    plan = json.loads(args.plan.read_text())
    digest = plan_digest(args.plan)
    # absolute: the pane starts in the disposable project directory
    runner_binary = Path(args.runner).resolve()
    for required in (TMUX, PROBE, runner_binary):
        if not required.exists():
            print(f"missing {required}", file=sys.stderr)
            return 2
    expected_tmux = (TMUX.parent / (TMUX.name + ".sha256")).read_text().split()[0]
    if sha256_file(TMUX) != expected_tmux:
        print("bundled tmux does not match its pinned SHA-256", file=sys.stderr)
        return 2

    if args.mode == "ci":
        records, complete = run_ci(args, plan, digest, runner_binary)
    else:
        records, complete = run_designated(args, plan, digest, runner_binary)
    with open(args.out, "w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, sort_keys=True) + "\n")

    if args.app_probe and args.mode == "ci":
        app_out = Path(str(args.out) + ".app.jsonl")
        app_out.unlink(missing_ok=True)
        admission = [case["id"] for case in plan["cases"] if "B-admission" in case["lanes"]]
        if len(admission) != 1:
            print("the plan must name exactly one B-admission case", file=sys.stderr)
            return 2
        result = subprocess.run(
            ["cargo", "test", "--locked", "--manifest-path", str(TAURI / "Cargo.toml"), "-p", "deck-app", "--bin", "deck-app",
             "ce1_probe_", "--", "--test-threads=1"],
            env={**os.environ, "DECK_CE_EVIDENCE": str(app_out), "DECK_CE_PLAN_DIGEST": digest,
                 "DECK_CE_DECK_BUILD": args.deck_build, "DECK_CE_PLAN_ID": plan["id"],
                 "DECK_CE_CASE": admission[0]},
            capture_output=True, text=True,
        )
        if result.returncode != 0 or not app_out.exists():
            print("the deck-app ce1 probe did not record evidence", file=sys.stderr)
            complete = False
        else:
            print(f"app evidence: {app_out}")
    print(f"evidence: {args.out} ({'complete' if complete else 'INCOMPLETE'})")
    return 0 if complete else 1


if __name__ == "__main__":
    sys.exit(main())
